In [510]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_columns', 50)
from datetime import timezone 
import re
import datetime

In [511]:
df=pd.read_csv("data/METAR_all_airports.csv",sep=',')
df

,AIRPORT_IATA,AIRPORT_ICAO,UTC DATE/TIME,METAR,DESCRIPTION
0,LHR,EGLL,5/18/2019 23:50,EGLL 182350Z AUTO 01003KT 9999 NCD 11/09 Q1009...,Day: 18th Time: 23:50 UTC Wind direction: 10 W...
1,LHR,EGLL,5/18/2019 23:20,EGLL 182320Z AUTO 02002KT 9999 NCD 10/08 Q1009...,Day: 18th Time: 23:20 UTC Wind direction: 20 W...
2,LHR,EGLL,5/18/2019 22:50,EGLL 182250Z AUTO 04002KT 9999 NCD 12/09 Q1009...,Day: 18th Time: 22:50 UTC Wind direction: 40 W...
3,LHR,EGLL,5/18/2019 22:20,EGLL 182220Z AUTO 06002KT 9999 NCD 12/09 Q1008,Day: 18th Time: 22:20 UTC Wind direction: 60 W...
4,LHR,EGLL,5/18/2019 21:50,EGLL 182150Z AUTO VRB02KT 9999 NCD 13/09 Q1008...,Day: 18th Time: 21:50 UTC Wind speed: 2kt Temp...
...,...,...,...,...,...
13472,IBZ,LEIB,6/5/2019 2:00,LEIB 050200Z 20005KT 160V230 9999 FEW008 BKN00...,Day: 5th Time: 02:00 UTC Wind direction: 200 W...
13473,IBZ,LEIB,6/5/2019 1:30,LEIB 050130Z 21005KT 170V260 9999 FEW008 BKN00...,Day: 5th Time: 01:30 UTC Wind direction: 210 W...
13474,IBZ,LEIB,6/5/2019 1:00,LEIB 050100Z 19006KT 140V230 9999 SCT008 BKN00...,Day: 5th Time: 01:00 UTC Wind direction: 190 W...
13475,IBZ,LEIB,6/5/2019 0:30,LEIB 050030Z 20006KT 150V230 9999 SCT008 BKN00...,Day: 5th Time: 00:30 UTC Wind direction: 200 W...
13476,IBZ,LEIB,6/5/2019 0:00,LEIB 050000Z 21005KT 170V250 9999 SCT007 BKN00...,Day: 5th Time: 00:00 UTC Wind direction: 210 W...

In [512]:
df['UTC DATE/TIME'] = pd.to_datetime(df['UTC DATE/TIME'])

for i in range(df.shape[0]):
    dt = df['UTC DATE/TIME'][i]
    utc_time = dt.replace(tzinfo = timezone.utc) 
    df['UTC DATE/TIME'][i] = int(utc_time.timestamp())

C:\Users\vivek\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\vivek\Anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [513]:
df['UTC DATE/TIME'][0]

1558223400

In [514]:
df

,AIRPORT_IATA,AIRPORT_ICAO,UTC DATE/TIME,METAR,DESCRIPTION
0,LHR,EGLL,1558223400,EGLL 182350Z AUTO 01003KT 9999 NCD 11/09 Q1009...,Day: 18th Time: 23:50 UTC Wind direction: 10 W...
1,LHR,EGLL,1558221600,EGLL 182320Z AUTO 02002KT 9999 NCD 10/08 Q1009...,Day: 18th Time: 23:20 UTC Wind direction: 20 W...
2,LHR,EGLL,1558219800,EGLL 182250Z AUTO 04002KT 9999 NCD 12/09 Q1009...,Day: 18th Time: 22:50 UTC Wind direction: 40 W...
3,LHR,EGLL,1558218000,EGLL 182220Z AUTO 06002KT 9999 NCD 12/09 Q1008,Day: 18th Time: 22:20 UTC Wind direction: 60 W...
4,LHR,EGLL,1558216200,EGLL 182150Z AUTO VRB02KT 9999 NCD 13/09 Q1008...,Day: 18th Time: 21:50 UTC Wind speed: 2kt Temp...
...,...,...,...,...,...
13472,IBZ,LEIB,1559700000,LEIB 050200Z 20005KT 160V230 9999 FEW008 BKN00...,Day: 5th Time: 02:00 UTC Wind direction: 200 W...
13473,IBZ,LEIB,1559698200,LEIB 050130Z 21005KT 170V260 9999 FEW008 BKN00...,Day: 5th Time: 01:30 UTC Wind direction: 210 W...
13474,IBZ,LEIB,1559696400,LEIB 050100Z 19006KT 140V230 9999 SCT008 BKN00...,Day: 5th Time: 01:00 UTC Wind direction: 190 W...
13475,IBZ,LEIB,1559694600,LEIB 050030Z 20006KT 150V230 9999 SCT008 BKN00...,Day: 5th Time: 00:30 UTC Wind direction: 200 W...
13476,IBZ,LEIB,1559692800,LEIB 050000Z 21005KT 170V250 9999 SCT007 BKN00...,Day: 5th Time: 00:00 UTC Wind direction: 210 W...

In [515]:
def regex1(raw):
    p=re.search(r"([0-9]{3}|VRB)([0-9]{2,3})G?([0-9]{2,3})?(KT|MPS|KMH)", raw)
    if (p):
        return(p.group())
    else:
        return
df['Wind']=df['METAR'].apply(regex1)
df['Wind'] = df['Wind'].astype(str)

In [516]:
def regex1(raw):
    p=re.search(r"([0-9]{3}|VRB)?", raw)
    if (p):
        return(p.group())
    else:
        return
df['Wind_Speed']=df['Wind'].apply(regex1)

In [517]:
def regex1(raw):
    p=re.search(r"([0-9]{2}(?=(KT|MPS|KMH)))", raw)
    if (p):
        return(p.group())
    else:
        return
df['Wind_direction']=df['Wind'].apply(regex1)

In [518]:
df.drop('Wind', axis = 1, inplace = True)

In [519]:
def regex1(raw):
    p=re.search(r"(( [0-9]{4} )|CAVOK|( [0-9./]+\s*SM))", raw)
    if (p):
        return(p.group())
    else:
        return
df['Visibility']=df['METAR'].apply(regex1)

In [520]:
def regex1(raw):
    p=re.search(r"(M?[0-9]{2})/M?([0-9]{2})", raw)
    if (p):
        return(p.group())
    else:
        return
df['Temp']=df['METAR'].apply(regex1)
df['Temp'] = df['Temp'].astype(str)

In [521]:
'''
def regex1(raw):
    p=re.search(r"^(VV|FEW|SCT|SKC|CLR||BKN|OVC)([0-9]{3}|///)(CU|CB|TCU|CI)?$", raw)
    if (p):
        return(p.group())
    else:
        return
df['Clouds']=df['METAR'].apply(regex1)
'''

'\ndef regex1(raw):\n    p=re.search(r"^(VV|FEW|SCT|SKC|CLR||BKN|OVC)([0-9]{3}|///)(CU|CB|TCU|CI)?$", raw)\n    if (p):\n        return(p.group())\n    else:\n        return\ndf[\'Clouds\']=df[\'METAR\'].apply(regex1)\n'

In [522]:
def regex1(raw):
    p=re.search(r"(M?[0-9]{2})?", raw)
    if (p):
        return(p.group())
    else:
        return
    
df['Temperature']=df['Temp'].apply(regex1)

In [523]:
def regex1(raw):
    p=re.search(r"(?<=/)(M?[0-9]{2})", raw)
    if (p):
        return(p.group())
    else:
        return
    
df['Dew']=df['Temp'].apply(regex1)

In [524]:
df.drop('Temp', axis = 1, inplace = True)

In [525]:
def regex1(raw):
    p=re.search(r"(A([0-9]{4})|Q([0-9]{4}))", raw)
    if (p):
        return(p.group())
    else:
        return
df['Pressure']=df['METAR'].apply(regex1)

In [526]:
rex = r"(( [0-9]{4} )|CAVOK|( [0-9.]+\s*SM ))"
#rex = r"([0-9]{3}|VRB)([0-9]{2,3})(?=([0-9]+(KT|MPS|KMH)))"
p=re.search(rex, 'EGLL 181520Z AUTO 29006KT 25 SM FEW049/// //////CB 17/09 Q1006') # thi matches - it should not 06002KT
print(p)

<re.Match object; span=(25, 32), match=' 25 SM '>

In [527]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13477 entries, 0 to 13476
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   AIRPORT_IATA    13477 non-null  object
 1   AIRPORT_ICAO    13477 non-null  object
 2   UTC DATE/TIME   13477 non-null  object
 3   METAR           13477 non-null  object
 4   DESCRIPTION     13477 non-null  object
 5   Wind_Speed      13477 non-null  object
 6   Wind_direction  13472 non-null  object
 7   Visibility      13475 non-null  object
 8   Temperature     13477 non-null  object
 9   Dew             13475 non-null  object
 10  Pressure        13476 non-null  object
dtypes: object(11)
memory usage: 1.1+ MB

In [528]:
df.isnull().sum(axis=0)

AIRPORT_IATA      0
AIRPORT_ICAO      0
UTC DATE/TIME     0
METAR             0
DESCRIPTION       0
Wind_Speed        0
Wind_direction    5
Visibility        2
Temperature       0
Dew               2
Pressure          1
dtype: int64

In [529]:
df['Wind_direction'].fillna(0, inplace=True)
df['Visibility'].fillna(9999, inplace=True)
df['Dew'].fillna(0, inplace=True)
df['Pressure'].fillna(109, inplace=True)


# do it visually

In [531]:
df.head()

,AIRPORT_IATA,AIRPORT_ICAO,UTC DATE/TIME,METAR,DESCRIPTION,Wind_Speed,Wind_direction,Visibility,Temperature,Dew,Pressure
0,LHR,EGLL,1558223400,EGLL 182350Z AUTO 01003KT 9999 NCD 11/09 Q1009...,Day: 18th Time: 23:50 UTC Wind direction: 10 W...,010,03,9999,11,09,Q1009
1,LHR,EGLL,1558221600,EGLL 182320Z AUTO 02002KT 9999 NCD 10/08 Q1009...,Day: 18th Time: 23:20 UTC Wind direction: 20 W...,020,02,9999,10,08,Q1009
2,LHR,EGLL,1558219800,EGLL 182250Z AUTO 04002KT 9999 NCD 12/09 Q1009...,Day: 18th Time: 22:50 UTC Wind direction: 40 W...,040,02,9999,12,09,Q1009
3,LHR,EGLL,1558218000,EGLL 182220Z AUTO 06002KT 9999 NCD 12/09 Q1008,Day: 18th Time: 22:20 UTC Wind direction: 60 W...,060,02,9999,12,09,Q1008
4,LHR,EGLL,1558216200,EGLL 182150Z AUTO VRB02KT 9999 NCD 13/09 Q1008...,Day: 18th Time: 21:50 UTC Wind speed: 2kt Temp...,VRB,02,9999,13,09,Q1008

In [490]:
df.to_csv(r'data/METAR_airports.csv',index=False)